import React from 'react';

const SingleGame = () => {
    return (
        <div>
            <h2>This is Single Game Page</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Condimentum vitae sapien pellentesque habitant morbi. Eleifend mi in nulla posuere sollicitudin aliquam. Auctor neque vitae tempus quam pellentesque nec nam aliquam sem. Interdum varius sit amet mattis. Eu ultrices vitae auctor eu augue ut lectus arcu. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra accumsan. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Interdum velit euismod in pellentesque. Dictum fusce ut placerat orci nulla pellentesque dignissim. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Iaculis nunc sed augue lacus. Sapien et ligula ullamcorper malesuada proin. Ac placerat vestibulum lectus mauris ultrices eros. Eu lobortis elementum nibh tellus. Integer vitae justo eget magna fermentum iaculis eu non. Urna porttitor rhoncus dolor purus.</p>
            <p>Sed id semper risus in. Mi tempus imperdiet nulla malesuada. Pharetra vel turpis nunc eget. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Elementum integer enim neque volutpat ac. Tortor id aliquet lectus proin nibh nisl condimentum id venenatis. Enim neque volutpat ac tincidunt vitae. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Aliquet enim tortor at auctor urna nunc. Sit amet massa vitae tortor condimentum lacinia quis. Varius sit amet mattis vulputate enim. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. Proin sed libero enim sed faucibus turpis in. Mattis rhoncus urna neque viverra justo nec.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Condimentum vitae sapien pellentesque habitant morbi. Eleifend mi in nulla posuere sollicitudin aliquam. Auctor neque vitae tempus quam pellentesque nec nam aliquam sem. Interdum varius sit amet mattis. Eu ultrices vitae auctor eu augue ut lectus arcu. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra accumsan. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Interdum velit euismod in pellentesque. Dictum fusce ut placerat orci nulla pellentesque dignissim. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Iaculis nunc sed augue lacus. Sapien et ligula ullamcorper malesuada proin. Ac placerat vestibulum lectus mauris ultrices eros. Eu lobortis elementum nibh tellus. Integer vitae justo eget magna fermentum iaculis eu non. Urna porttitor rhoncus dolor purus.</p>
            <p>Sed id semper risus in. Mi tempus imperdiet nulla malesuada. Pharetra vel turpis nunc eget. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Elementum integer enim neque volutpat ac. Tortor id aliquet lectus proin nibh nisl condimentum id venenatis. Enim neque volutpat ac tincidunt vitae. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Aliquet enim tortor at auctor urna nunc. Sit amet massa vitae tortor condimentum lacinia quis. Varius sit amet mattis vulputate enim. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. Proin sed libero enim sed faucibus turpis in. Mattis rhoncus urna neque viverra justo nec.</p>
        </div>
    );
}

export default SingleGame;
